### PR TITLE
Spin axis bug

### LINKED ISSUE #49: Rotation inverted? 🤔
Was wondering, shouldn't we need to rotate the point in the opposite direction as the bodies rotation? 🤔 

https://github.com/rasmusmarak/TOSS/blob/2501351468eb362fa9ec8217b2fc426db37fca9a/toss/trajectory/equations_of_motion.py#L81

Might be wrong, just to doublecheck

### LINKED ISSUE #50: Error in formulation of spin axis
https://github.com/rasmusmarak/TOSS/blob/2501351468eb362fa9ec8217b2fc426db37fca9a/toss/trajectory/equations_of_motion.py#L27-L32

You use above code to compute the spin axis. However, I don't think it is correct, e.g.

```py
from pyquaternion import Quaternion
from math import radians
 # Setup spin axis of the body
declination = 90
right_ascension = 0
q_dec = Quaternion(axis=[1,0,0], angle=radians(declination)) # Rotate spin axis according to declination
q_ra = Quaternion(axis=[0,0,1], angle=radians(right_ascension)) # Rotate spin axis accordining to right ascension
q_axis = q_dec * q_ra  # Composite rotation of q1 then q2 expressed as standard multiplication
spin_axis = q_axis.rotate([0,0,1])
print(spin_axis)
```

Returns `[0.0, -1.0000000000000002, 0.0]`

while it should be `[0,0,1]`?

Or e.g.
```
declination = 45
right_ascension = 90
```
leads to `[0.0, -0.7071067811865476, 0.7071067811865476]`

but should be 

`[0 7.07106781e-01 7.07106781e-01]`?

### PR DESCRIPTION
**Pull request by rasmusmarak**
# Description

Updated spin axis according to bug described in #50.

Summary of changes
* Changes spin-axis setup to the one mentioned in https://github.com/rasmusmarak/TOSS/issues/50#issuecomment-1640260683
* Updated all of the tests for the new spin-axis.
* Added a new sanity test for setting up a spin-axis
* Reversed rotation of positions with respect to the body's rotation. 

## Resolved Issues
- Fixes #50 
- Fixes #49 

## How Has This Been Tested?
- A new spin-axis sanity test. Verifies that the function results in a known axis for given values on right ascension and declination.

### CODE REVIEW

**Comment by rasmusmarak** [comment]
Oh seems like this PR inherited the commits from #46 since I branched out from there. The only new commits on this branch are from "corrected spin axis" ([4f1d570](https://github.com/rasmusmarak/TOSS/pull/51/commits/4f1d5707a4f3b1b0899cdb1ee87cc2f050a7623f)) and to "added spin axis test" ([6ef5f61](https://github.com/rasmusmarak/TOSS/pull/51/commits/6ef5f615d9b93e7c775f64c00aade41001a113b4))

**Review by gomezzz — APPROVED** [review]
I trust that you double-checked my math :D :P

**Comment by rasmusmarak** [comment]
I went through the math last week and it seems to be right for when we want to rotate the z-axis by some given declination and right-ascension in order to represent the spin axis. 

However, when doing the math for the thesis report, two potential issues occurred to me:

1. Is the mesh centered according its center of mass? (Fortunately, I found out that it was which solves that issue.) 
3. In which reference frame is the mesh defined in? 

The second question is perhaps more focused on the realism of the defined rotation axis. It would be nice to know whether it is defined in something like the Hill frame with respect to the sun, or perhaps the small-body inertial frame. In the latter case, it might be that the z-axis (or similar) already account for the Dec/RA and defines the rotation axis. Do you happen to know which frame it is defined in?

As complementary material, Jonas also found this link which discusses the frames a bit. But I am not sure I completely understood their transformations and which frame things were defined in. https://github.com/darioizzo/geodesyNets/blob/master/archive/Modelling%20Churyumov-Gerasimenko%20with%20mascons.ipynb

**Comment by gomezzz** [comment]
> Is the mesh centered according its center of mass? (Fortunately, I found out that it was which solves that issue.)
:+1: 

2. See here https://github.com/rasmusmarak/TOSS/issues/10 , not sure where the mesh came from? Probably from the original paper, then the source and coordinate frame should be defined there

**Comment by gomezzz** [comment]
> As complementary material, Jonas also found this link which discusses the frames a bit. But I am not sure I completely understood their transformations and which frame things were defined in. https://github.com/darioizzo/geodesyNets/blob/master/archive/Modelling%20Churyumov-Gerasimenko%20with%20mascons.ipynb

Oh actually it may have been transformed. I am not sure then actually. Either, try to track down which frame the one you have is in or find another one where you know ;)

**Comment by rasmusmarak** [comment]
Still not completely sure which axis is the correct axis of rotation. I will add a few plots from various sources below.

For instance, comparing the plots below, it seems that the first source suggest that the current z-axis of the mesh is the axis of rotations, whereas the ESA source seems to be more compatible with the orange (current) spin axis.


**Plot from TOSS:**
(red=x_axis, green=y_axis, blue=z_axis, orange=spin_axis)
mesh_prinicpal_axes


**Source 1:**
https://www.aanda.org/articles/aa/full_html/2015/07/aa26421-15/F1.html

Rotation axis = z_axis in plot.
Skärmavbild 2023-08-21 kl  14 06 49


**Source 2:**
ESA


67p_rotation_axis

**Comment by rasmusmarak** [comment]
Furthermore, it was also mentioned in the geodesyNets paper that the mesh was defined in the inertial frame with the principal axes plotted as below. From this comparison, it is evident that our mesh is defined in the same frame as was used in geodesynets. However, I could not find any info about the axis of rotation in neither the geodesyNets papers nor the GitHub repo.

**GeodesyNet**
Paper: "Geodesy of irregular small bodies via neural density fields: geodesyNets"
Skärmavbild 2023-08-21 kl  14 14 57


**Current mesh from the same angle:**
mesh_prinicpal_axies_second_view

**Comment by rasmusmarak** [comment]
By also looking at the following sources, 
https://www.aanda.org/articles/aa/pdf/2015/07/aa26421-15.pdf
https://www.sciencedirect.com/science/article/abs/pii/S0019103516301385
https://arxiv.org/pdf/1812.01490.pdf
https://sci.esa.int/web/rosetta/-/14615-comet-67p
it seems that that the current spin axis may be valid. The real spin-axis of 67P varies over time and the distance to the sun etc, for instance, the spin axis was found to be oriented in the Equatorial direction (RA, Dec) = (220◦,−70◦) for the retrograde solution and (RA, Dec) = (40◦,+70◦) for the prograde one. 

In another paper (https://arxiv.org/pdf/1812.01490.pdf), they assume the initial orientation of the rotation axis in the equatorial frame to be set to be in the lowest energy state (rotation axis and angular momentum aligned, pointing to RA α = 69.427◦, Dec δ = 64.000◦ at t = −350 days). Looking at the diagrams on how the rotation axis changes according to this paper, see **Fig 2**, and how the rotational period is relatively fixed for the mission duration that we consider in our study, see **Fig 7,** we can probably assume a fixed orientation and period for our simulation. 

This findings seems to follow the same pattern as was presented here (https://www.sciencedirect.com/science/article/pii/S0019103516301385?ref=pdf_download&fr=RR-2&rr=7fa31a0e3f080a1d, p.273-274), but where they now assume the z-axis to be defined in a different direction (=y-axis in our plot). But they still refer to this axis being shifted to the same RA/DEC = (69/64)

And since ESA provided the same RA and DEC values at their webpage (https://sci.esa.int/web/rosetta/-/14615-comet-67p), with the spin axis (https://sci.esa.int/web/rosetta/-/56181-comet-67p-rotation-and-regions) seemingly being aligned with the one we have defined with the same DEC/RA (the one in orange), we can probably use that one hereafter.

**Comment by rasmusmarak** [comment]
What do you think?

**Comment by gomezzz** [comment]
> However, I could not find any info about the axis of rotation in neither the geodesyNets papers nor the GitHub repo.

Rotation was not considered in the paper.

> What do you think?

Not sure if I am quite following it all. If you are unsure about the mesh frame, I would suggest to use a different one where it is clearly defined, probably some of the papers you link provide one? If you are confident about it and have a good matching reference then go with it. 

Whichever route you take, please also mention in https://github.com/gomezzz/GravitySwarming/issues/19 Thanks!

**Review by gomezzz — APPROVED** [review]

**Pull request merged**
